-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  category text NOT NULL CHECK (category = ANY (ARRAY['performance'::text, 'consistency'::text, 'excellence'::text, 'community'::text, 'special'::text])),
  achievement_type text NOT NULL CHECK (achievement_type = ANY (ARRAY['helper'::text, 'customer'::text, 'both'::text])),
  unlock_criteria jsonb NOT NULL,
  reward_points integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.background_check_results (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  check_type text NOT NULL CHECK (check_type = ANY (ARRAY['identity'::text, 'criminal'::text, 'address'::text, 'employment'::text, 'references'::text, 'driving_license'::text])),
  provider text,
  provider_request_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'verified'::text, 'rejected'::text, 'expired'::text])),
  verification_score integer CHECK (verification_score >= 0 AND verification_score <= 100),
  details jsonb,
  verified_data jsonb,
  rejection_reason text,
  verified_by uuid,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT background_check_results_pkey PRIMARY KEY (id),
  CONSTRAINT background_check_results_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id),
  CONSTRAINT background_check_results_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.badge_definitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  icon_url text,
  badge_type text NOT NULL CHECK (badge_type = ANY (ARRAY['helper'::text, 'customer'::text, 'both'::text])),
  requirement_type text NOT NULL CHECK (requirement_type = ANY (ARRAY['jobs_completed'::text, 'rating_threshold'::text, 'earnings_milestone'::text, 'referrals'::text, 'consecutive_days'::text, 'specialization_verified'::text])),
  requirement_value integer NOT NULL,
  rarity text NOT NULL CHECK (rarity = ANY (ARRAY['common'::text, 'rare'::text, 'epic'::text, 'legendary'::text])),
  points_value integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT badge_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bid_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  application_id uuid NOT NULL,
  bid_amount numeric NOT NULL,
  bid_breakdown jsonb DEFAULT '{}'::jsonb,
  proposed_by uuid NOT NULL,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT bid_history_pkey PRIMARY KEY (id),
  CONSTRAINT bid_history_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.request_applications(id),
  CONSTRAINT bid_history_proposed_by_fkey FOREIGN KEY (proposed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bundle_purchases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bundle_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  purchase_price numeric NOT NULL,
  payment_id uuid,
  valid_until timestamp with time zone,
  services_used integer DEFAULT 0,
  services_total integer NOT NULL,
  is_expired boolean DEFAULT false,
  purchased_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT bundle_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT bundle_purchases_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES public.service_bundles(id),
  CONSTRAINT bundle_purchases_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT bundle_purchases_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payment_orders(id)
);
CREATE TABLE public.bundle_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bundle_id uuid NOT NULL,
  category_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  individual_price numeric NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT bundle_services_pkey PRIMARY KEY (id),
  CONSTRAINT bundle_services_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES public.service_bundles(id),
  CONSTRAINT bundle_services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.call_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  metric_name text NOT NULL,
  metric_value jsonb NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT call_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT call_analytics_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.video_call_sessions(id)
);
CREATE TABLE public.call_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['host'::text, 'participant'::text, 'observer'::text])),
  joined_at timestamp with time zone,
  left_at timestamp with time zone,
  duration_seconds integer,
  connection_quality text CHECK (connection_quality = ANY (ARRAY['excellent'::text, 'good'::text, 'fair'::text, 'poor'::text])),
  device_info jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT call_participants_pkey PRIMARY KEY (id),
  CONSTRAINT call_participants_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.video_call_sessions(id),
  CONSTRAINT call_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.call_recordings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  recording_type text NOT NULL CHECK (recording_type = ANY (ARRAY['video'::text, 'audio'::text, 'screen_share'::text])),
  file_url text NOT NULL,
  file_size_bytes bigint,
  duration_seconds integer,
  format text,
  storage_provider text CHECK (storage_provider = ANY (ARRAY['supabase'::text, 's3'::text, 'azure'::text, 'gcs'::text])),
  is_available boolean DEFAULT true,
  expires_at timestamp with time zone,
  download_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT call_recordings_pkey PRIMARY KEY (id),
  CONSTRAINT call_recordings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.video_call_sessions(id)
);
CREATE TABLE public.campaign_applicable_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  category_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT campaign_applicable_services_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_applicable_services_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.seasonal_campaigns(id),
  CONSTRAINT campaign_applicable_services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.campaign_redemptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  request_id uuid,
  discount_applied numeric NOT NULL,
  original_amount numeric NOT NULL,
  final_amount numeric NOT NULL,
  redeemed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT campaign_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_redemptions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.seasonal_campaigns(id),
  CONSTRAINT campaign_redemptions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT campaign_redemptions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id)
);
CREATE TABLE public.commission_settings (
  id integer NOT NULL DEFAULT nextval('commission_settings_id_seq'::regclass),
  percent numeric NOT NULL CHECK (percent >= 0::numeric AND percent <= 100::numeric),
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  surge_multiplier numeric DEFAULT 1.5 CHECK (surge_multiplier >= 1.0 AND surge_multiplier <= 5.0),
  service_radius_km integer DEFAULT 10 CHECK (service_radius_km >= 1 AND service_radius_km <= 100),
  emergency_radius_km integer DEFAULT 20 CHECK (emergency_radius_km >= 1 AND emergency_radius_km <= 100),
  min_withdrawal_amount integer DEFAULT 100 CHECK (min_withdrawal_amount >= 1),
  auto_payout_threshold integer DEFAULT 1000 CHECK (auto_payout_threshold >= 100),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commission_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::subscription_status,
  started_at timestamp with time zone,
  expires_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  next_billing_at timestamp with time zone,
  last_billing_at timestamp with time zone,
  cashfree_subscription_id text,
  renewal_order_id text,
  interval USER-DEFINED NOT NULL,
  price_rupees numeric NOT NULL,
  applied_priority_level integer,
  included_features ARRAY DEFAULT ARRAY[]::feature_key[],
  trial_ends_at timestamp with time zone,
  discount_percent numeric,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT customer_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_subscriptions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT customer_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.device_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token text NOT NULL,
  provider text DEFAULT 'fcm'::text,
  device_type text,
  is_active boolean DEFAULT true,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT device_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.escrows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  helper_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  status USER-DEFINED NOT NULL DEFAULT 'funded'::escrow_status,
  cashfree_order_id text,
  cashfree_payment_id text,
  funded_at timestamp with time zone NOT NULL DEFAULT now(),
  released_at timestamp with time zone,
  refunded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT escrows_pkey PRIMARY KEY (id),
  CONSTRAINT escrows_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT escrows_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT escrows_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.geofence_violations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  violation_type text NOT NULL CHECK (violation_type = ANY (ARRAY['arrival_location_mismatch'::text, 'work_outside_radius'::text, 'false_arrival_claim'::text])),
  expected_location USER-DEFINED,
  actual_location USER-DEFINED,
  distance_meters numeric,
  threshold_meters numeric,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  action_taken text CHECK (action_taken = ANY (ARRAY['warning'::text, 'fine'::text, 'suspension'::text, 'none'::text])),
  admin_notes text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT geofence_violations_pkey PRIMARY KEY (id),
  CONSTRAINT geofence_violations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT geofence_violations_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_bank_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  account_holder_name text NOT NULL,
  account_number text,
  ifsc_code character varying,
  bank_name text,
  branch_name text,
  upi_id character varying,
  is_primary boolean DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'pending_verification'::bank_account_status,
  rejected_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT helper_bank_accounts_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  service_categories ARRAY DEFAULT '{}'::text[],
  skills ARRAY DEFAULT '{}'::text[],
  experience_years integer,
  hourly_rate numeric,
  service_radius integer DEFAULT 10,
  is_approved boolean DEFAULT false,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  rating_sum integer NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0,
  latitude numeric,
  longitude numeric,
  service_radius_km integer DEFAULT 10,
  address text,
  pincode character varying,
  service_areas ARRAY DEFAULT '{}'::text[],
  working_hours jsonb DEFAULT '{"friday": {"end": "18:00", "start": "09:00", "available": true}, "monday": {"end": "18:00", "start": "09:00", "available": true}, "sunday": {"end": "18:00", "start": "09:00", "available": false}, "tuesday": {"end": "18:00", "start": "09:00", "available": true}, "saturday": {"end": "18:00", "start": "09:00", "available": true}, "thursday": {"end": "18:00", "start": "09:00", "available": true}, "wednesday": {"end": "18:00", "start": "09:00", "available": true}}'::jsonb,
  emergency_availability boolean DEFAULT false,
  is_available_now boolean DEFAULT true,
  skills_specialization ARRAY DEFAULT '{}'::text[],
  years_of_experience integer,
  total_jobs_completed integer DEFAULT 0,
  response_rate_percent numeric DEFAULT 100.0,
  completion_rate_percent numeric DEFAULT 100.0,
  average_response_minutes integer,
  service_area_ids ARRAY DEFAULT '{}'::uuid[],
  instant_booking_enabled boolean DEFAULT false,
  instant_booking_price numeric,
  instant_booking_duration_minutes integer,
  available_time_slots jsonb DEFAULT '[]'::jsonb,
  auto_accept_enabled boolean DEFAULT false,
  max_concurrent_bookings integer DEFAULT 3,
  response_time_minutes integer DEFAULT 30,
  CONSTRAINT helper_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT helper_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_rating_summary (
  helper_id uuid NOT NULL,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  rating_5_count integer DEFAULT 0,
  rating_4_count integer DEFAULT 0,
  rating_3_count integer DEFAULT 0,
  rating_2_count integer DEFAULT 0,
  rating_1_count integer DEFAULT 0,
  avg_quality numeric DEFAULT 0,
  avg_timeliness numeric DEFAULT 0,
  avg_professionalism numeric DEFAULT 0,
  avg_value numeric DEFAULT 0,
  last_review_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_rating_summary_pkey PRIMARY KEY (helper_id),
  CONSTRAINT helper_rating_summary_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  category_id uuid NOT NULL,
  hourly_rate numeric NOT NULL,
  experience_years integer,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  custom_price numeric,
  price_type USER-DEFINED DEFAULT 'per_hour'::price_type,
  min_price numeric,
  service_description text,
  supports_emergency boolean DEFAULT false,
  emergency_price_multiplier numeric DEFAULT 1.5,
  response_time_minutes integer DEFAULT 60,
  is_available boolean DEFAULT true,
  CONSTRAINT helper_services_pkey PRIMARY KEY (id),
  CONSTRAINT helper_services_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_specializations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  category_id uuid NOT NULL,
  experience_years integer DEFAULT 0,
  completed_jobs_count integer DEFAULT 0,
  certification_url text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_specializations_pkey PRIMARY KEY (id),
  CONSTRAINT helper_specializations_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_statistics (
  helper_id uuid NOT NULL,
  total_jobs_completed integer DEFAULT 0,
  total_jobs_assigned integer DEFAULT 0,
  completion_rate numeric DEFAULT 0,
  total_earnings numeric DEFAULT 0,
  avg_job_duration_minutes integer DEFAULT 0,
  cancellation_count integer DEFAULT 0,
  late_arrival_count integer DEFAULT 0,
  on_time_percentage numeric DEFAULT 100,
  response_time_avg_minutes integer DEFAULT 0,
  last_active_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_statistics_pkey PRIMARY KEY (helper_id),
  CONSTRAINT helper_statistics_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.helper_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::subscription_status,
  started_at timestamp with time zone,
  expires_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  next_billing_at timestamp with time zone,
  last_billing_at timestamp with time zone,
  cashfree_subscription_id text,
  renewal_order_id text,
  interval USER-DEFINED NOT NULL,
  price_rupees numeric NOT NULL,
  applied_commission_discount_percent numeric,
  applied_extra_radius_km integer,
  applied_priority_level integer,
  included_features ARRAY DEFAULT ARRAY[]::feature_key[],
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT helper_subscriptions_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id),
  CONSTRAINT helper_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.helper_trust_scores (
  helper_id uuid NOT NULL,
  overall_score integer DEFAULT 0 CHECK (overall_score >= 0 AND overall_score <= 100),
  background_check_score integer DEFAULT 0,
  document_verification_score integer DEFAULT 0,
  behavior_score integer DEFAULT 100,
  customer_feedback_score integer DEFAULT 0,
  geofence_compliance_score integer DEFAULT 100,
  total_violations integer DEFAULT 0,
  active_warnings integer DEFAULT 0,
  suspension_count integer DEFAULT 0,
  last_violation_at timestamp with time zone,
  last_calculated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT helper_trust_scores_pkey PRIMARY KEY (helper_id),
  CONSTRAINT helper_trust_scores_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.insurance_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  insurance_id uuid NOT NULL,
  claim_type text NOT NULL CHECK (claim_type = ANY (ARRAY['damage'::text, 'theft'::text, 'injury'::text, 'other'::text])),
  claim_amount numeric NOT NULL,
  description text NOT NULL,
  evidence_urls jsonb,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'paid'::text])),
  admin_notes text,
  approved_amount numeric,
  rejection_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT insurance_claims_pkey PRIMARY KEY (id),
  CONSTRAINT insurance_claims_insurance_id_fkey FOREIGN KEY (insurance_id) REFERENCES public.service_insurance(id),
  CONSTRAINT insurance_claims_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.job_checkpoints (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  checkpoint_type text NOT NULL CHECK (checkpoint_type = ANY (ARRAY['arrived'::text, 'started'::text, 'pause'::text, 'resume'::text, 'issue_reported'::text, 'milestone'::text, 'completed'::text])),
  note text,
  location_lat numeric,
  location_lng numeric,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT job_checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT job_checkpoints_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT job_checkpoints_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.job_earnings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  gross_amount_paise integer NOT NULL,
  commission_paise integer NOT NULL,
  net_amount_paise integer NOT NULL,
  source USER-DEFINED NOT NULL DEFAULT 'service_completion'::earning_source,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::earning_status,
  notes text,
  recorded_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT job_earnings_pkey PRIMARY KEY (id),
  CONSTRAINT job_earnings_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT job_earnings_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ledger_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_id uuid NOT NULL,
  account_user_id uuid NOT NULL,
  balance_type text NOT NULL CHECK (balance_type = ANY (ARRAY['available'::text, 'escrow'::text])),
  delta numeric NOT NULL,
  balance_after numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ledger_entries_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_entries_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.payment_transactions(id),
  CONSTRAINT ledger_entries_account_user_id_fkey FOREIGN KEY (account_user_id) REFERENCES public.wallet_accounts(user_id)
);
CREATE TABLE public.legal_acceptances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  document_type USER-DEFINED NOT NULL,
  document_version integer NOT NULL,
  accepted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  ip inet,
  user_agent text,
  CONSTRAINT legal_acceptances_pkey PRIMARY KEY (id),
  CONSTRAINT legal_acceptances_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.legal_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type USER-DEFINED NOT NULL,
  version integer NOT NULL,
  title text NOT NULL,
  content_md text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  published_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT legal_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.login_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  success boolean NOT NULL,
  ip_address text,
  location text,
  user_agent text,
  failure_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT login_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT login_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.loyalty_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  points_earned integer NOT NULL DEFAULT 0,
  points_spent integer NOT NULL DEFAULT 0,
  points_balance integer NOT NULL DEFAULT 0,
  last_earned_at timestamp with time zone,
  last_spent_at timestamp with time zone,
  lifetime_points integer NOT NULL DEFAULT 0,
  tier_level text DEFAULT 'bronze'::text CHECK (tier_level = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['earn'::text, 'spend'::text, 'expire'::text, 'refund'::text])),
  points_amount integer NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['booking'::text, 'referral'::text, 'review'::text, 'badge'::text, 'achievement'::text, 'redemption'::text, 'promotion'::text, 'admin_adjustment'::text])),
  source_id uuid,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  read_at timestamp with time zone,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  attachment_url text,
  attachment_type text CHECK (attachment_type = ANY (ARRAY['image'::text, 'document'::text, 'audio'::text, 'video'::text])),
  attachment_name text,
  attachment_size integer,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_key text NOT NULL UNIQUE,
  channel USER-DEFINED NOT NULL,
  title text,
  body text NOT NULL,
  data_schema jsonb,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  request_id uuid,
  channel USER-DEFINED NOT NULL DEFAULT 'push'::notification_channel,
  title text,
  body text NOT NULL,
  data jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::notification_status,
  error text,
  sent_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id)
);
CREATE TABLE public.payment_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id character varying NOT NULL UNIQUE,
  cf_order_id character varying,
  request_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  helper_id uuid,
  order_amount integer NOT NULL,
  order_currency character varying DEFAULT 'INR'::character varying,
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  payment_method USER-DEFINED,
  payment_time timestamp with time zone,
  cf_payment_id character varying,
  bank_reference character varying,
  auth_id character varying,
  customer_name character varying,
  customer_email character varying,
  customer_phone character varying,
  order_note text,
  return_url text,
  notify_url text,
  payment_message text,
  failure_reason text,
  error_code character varying,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payment_orders_pkey PRIMARY KEY (id),
  CONSTRAINT payment_orders_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT payment_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_orders_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type USER-DEFINED NOT NULL,
  request_id uuid,
  initiator_id uuid,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT payment_transactions_initiator_id_fkey FOREIGN KEY (initiator_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_webhooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id character varying,
  event_type character varying NOT NULL,
  event_time timestamp with time zone NOT NULL,
  webhook_data jsonb NOT NULL,
  signature character varying,
  signature_verified boolean DEFAULT false,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  processing_error text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payment_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhooks_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.payment_orders(order_id)
);
CREATE TABLE public.payout_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  withdrawal_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  cashfree_payout_id text,
  status text NOT NULL DEFAULT 'initiated'::text CHECK (status = ANY (ARRAY['initiated'::text, 'success'::text, 'failed'::text])),
  initiated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  failure_reason text,
  raw_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payout_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payout_transactions_withdrawal_id_fkey FOREIGN KEY (withdrawal_id) REFERENCES public.withdrawal_requests(id),
  CONSTRAINT payout_transactions_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.phone_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  phone character varying NOT NULL,
  country_code character varying NOT NULL DEFAULT '+91'::character varying,
  otp_code character varying NOT NULL,
  otp_expires_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT phone_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT phone_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'customer'::user_role,
  full_name text,
  phone text,
  country_code text DEFAULT '+1'::text,
  avatar_url text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  phone_number character varying,
  phone_verified boolean DEFAULT false,
  phone_verified_at timestamp with time zone,
  status USER-DEFINED DEFAULT 'active'::user_status,
  is_banned boolean DEFAULT false,
  ban_reason text,
  banned_at timestamp with time zone,
  banned_by uuid,
  ban_expires_at timestamp with time zone,
  location_lat numeric,
  location_lng numeric,
  address text,
  city character varying,
  state character varying,
  pincode character varying,
  location_updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_banned_by_fkey FOREIGN KEY (banned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.promo_code_usages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  promo_id uuid NOT NULL,
  user_id uuid NOT NULL,
  request_id uuid,
  applied_amount_paise integer NOT NULL,
  order_amount_paise integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT promo_code_usages_pkey PRIMARY KEY (id),
  CONSTRAINT promo_code_usages_promo_id_fkey FOREIGN KEY (promo_id) REFERENCES public.promo_codes(id),
  CONSTRAINT promo_code_usages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT promo_code_usages_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type USER-DEFINED NOT NULL,
  discount_value numeric NOT NULL,
  max_discount_rupees numeric,
  start_date date NOT NULL,
  end_date date NOT NULL,
  usage_limit_total integer,
  usage_limit_per_user integer,
  min_order_amount_rupees numeric,
  allowed_roles ARRAY DEFAULT ARRAY['customer'::text],
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT promo_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.referral_rewards (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  referral_id uuid NOT NULL,
  referrer_id uuid NOT NULL,
  reward_type USER-DEFINED NOT NULL,
  amount_paise integer,
  linked_promo_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::reward_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  granted_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT referral_rewards_pkey PRIMARY KEY (id),
  CONSTRAINT referral_rewards_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id),
  CONSTRAINT referral_rewards_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_rewards_linked_promo_id_fkey FOREIGN KEY (linked_promo_id) REFERENCES public.promo_codes(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  referrer_id uuid NOT NULL,
  referred_user_id uuid,
  referral_code text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'initiated'::referral_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  converted_at timestamp with time zone,
  rewarded_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.refund_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  refund_id character varying NOT NULL UNIQUE,
  cf_refund_id character varying,
  order_id character varying NOT NULL,
  refund_amount integer NOT NULL,
  refund_reason text NOT NULL,
  refund_note text,
  refund_status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  refund_arn character varying,
  refund_processed_at timestamp with time zone,
  requested_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT refund_requests_pkey PRIMARY KEY (id),
  CONSTRAINT refund_requests_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.payment_orders(order_id),
  CONSTRAINT refund_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT refund_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.request_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'applied'::application_status,
  cover_note text,
  proposed_rate numeric,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  bid_amount numeric,
  bid_breakdown jsonb DEFAULT '{}'::jsonb,
  bid_valid_until timestamp with time zone,
  estimated_duration_hours integer,
  availability_note text,
  rejection_reason text,
  withdrawn_reason text,
  CONSTRAINT request_applications_pkey PRIMARY KEY (id),
  CONSTRAINT request_applications_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT request_applications_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.review_photos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  photo_url text NOT NULL,
  thumbnail_url text,
  caption text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT review_photos_pkey PRIMARY KEY (id),
  CONSTRAINT review_photos_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.seasonal_campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  campaign_type text NOT NULL CHECK (campaign_type = ANY (ARRAY['festival'::text, 'monsoon'::text, 'summer'::text, 'winter'::text, 'new_year'::text, 'special_event'::text, 'flash_sale'::text])),
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'flat'::text, 'bundle'::text])),
  discount_value numeric NOT NULL,
  min_order_amount numeric,
  max_discount_amount numeric,
  applicable_to text NOT NULL CHECK (applicable_to = ANY (ARRAY['all_services'::text, 'specific_services'::text, 'specific_categories'::text])),
  target_user_segment text CHECK (target_user_segment = ANY (ARRAY['all'::text, 'new_users'::text, 'existing_users'::text, 'premium_users'::text, 'inactive_users'::text])),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  banner_url text,
  terms_conditions text,
  max_redemptions_per_user integer DEFAULT 1,
  total_redemptions integer DEFAULT 0,
  total_revenue numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT seasonal_campaigns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_areas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  parent_id uuid,
  level character varying NOT NULL CHECK (level::text = ANY (ARRAY['state'::character varying, 'district'::character varying, 'city'::character varying, 'area'::character varying]::text[])),
  name character varying NOT NULL,
  slug character varying NOT NULL,
  latitude numeric,
  longitude numeric,
  pincode character varying,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_areas_pkey PRIMARY KEY (id),
  CONSTRAINT service_areas_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.service_areas(id)
);
CREATE TABLE public.service_bundles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  bundle_type text NOT NULL CHECK (bundle_type = ANY (ARRAY['combo'::text, 'package'::text, 'subscription'::text, 'seasonal'::text])),
  total_original_price numeric NOT NULL,
  bundle_price numeric NOT NULL,
  discount_percentage numeric DEFAULT 
CASE
    WHEN (total_original_price > (0)::numeric) THEN (((total_original_price - bundle_price) / total_original_price) * (100)::numeric)
    ELSE (0)::numeric
END,
  validity_days integer,
  max_redemptions integer,
  is_active boolean DEFAULT true,
  icon_url text,
  banner_url text,
  terms_conditions text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT service_bundles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  parent_id uuid,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  price_type USER-DEFINED DEFAULT 'per_hour'::price_type,
  unit_name text,
  base_price numeric,
  icon text,
  image_url text,
  requires_location boolean DEFAULT true,
  supports_emergency boolean DEFAULT false,
  display_order integer DEFAULT 0,
  CONSTRAINT service_categories_pkey PRIMARY KEY (id),
  CONSTRAINT service_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.service_insurance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  insurance_type text NOT NULL CHECK (insurance_type = ANY (ARRAY['damage_protection'::text, 'theft_protection'::text, 'personal_injury'::text, 'property_damage'::text])),
  coverage_amount numeric NOT NULL,
  premium_amount numeric NOT NULL,
  policy_number text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'claimed'::text, 'expired'::text, 'cancelled'::text])),
  valid_from timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  valid_until timestamp with time zone NOT NULL,
  terms_conditions text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT service_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT service_insurance_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT service_insurance_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT service_insurance_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.service_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  category_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  city text,
  country text,
  budget_min numeric,
  budget_max numeric,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::service_request_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  assigned_helper_id uuid,
  assigned_at timestamp with time zone,
  application_count integer NOT NULL DEFAULT 0,
  location_type USER-DEFINED DEFAULT 'home'::location_type,
  urgency_level USER-DEFINED DEFAULT 'normal'::urgency_level,
  latitude numeric,
  longitude numeric,
  address_line1 text,
  address_line2 text,
  landmark text,
  pincode character varying,
  state text,
  service_type_details jsonb DEFAULT '{}'::jsonb,
  quantity integer DEFAULT 1,
  estimated_price numeric,
  surge_multiplier numeric DEFAULT 1.0,
  preferred_date date,
  preferred_time_start time without time zone,
  preferred_time_end time without time zone,
  is_flexible boolean DEFAULT true,
  images ARRAY DEFAULT '{}'::text[],
  job_started_at timestamp with time zone,
  job_completed_at timestamp with time zone,
  job_duration_minutes integer,
  arrival_time timestamp with time zone,
  requires_proof boolean DEFAULT true,
  service_location_lat numeric,
  service_location_lng numeric,
  service_address text,
  service_city character varying,
  service_state character varying,
  service_pincode character varying,
  booking_type USER-DEFINED DEFAULT 'normal'::booking_type,
  instant_booking_confirmed_at timestamp with time zone,
  CONSTRAINT service_requests_pkey PRIMARY KEY (id),
  CONSTRAINT service_requests_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT service_requests_assigned_helper_id_fkey FOREIGN KEY (assigned_helper_id) REFERENCES public.profiles(id),
  CONSTRAINT service_requests_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.sla_configurations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  priority text NOT NULL UNIQUE CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  first_response_minutes integer NOT NULL,
  resolution_minutes integer NOT NULL,
  escalation_minutes integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sla_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sos_alerts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  request_id uuid,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['emergency'::text, 'safety_concern'::text, 'dispute'::text, 'harassment'::text, 'other'::text])),
  status USER-DEFINED NOT NULL DEFAULT 'active'::sos_status,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  address text,
  description text NOT NULL,
  contact_phone character varying,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  resolution_note text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sos_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT sos_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT sos_alerts_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT sos_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.profiles(id),
  CONSTRAINT sos_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.sos_evidence (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  alert_id uuid NOT NULL,
  media_url text NOT NULL,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text, 'audio'::text])),
  thumbnail_url text,
  caption text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sos_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT sos_evidence_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.sos_alerts(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.subscription_benefits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  plan_id uuid NOT NULL,
  benefit_type text NOT NULL CHECK (benefit_type = ANY (ARRAY['service_discount'::text, 'bundle_discount'::text, 'free_booking'::text, 'cashback'::text, 'priority_support'::text, 'extended_warranty'::text])),
  benefit_value jsonb NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_benefits_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_benefits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.subscription_feature_overrides (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  feature USER-DEFINED NOT NULL,
  value jsonb,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_feature_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_feature_overrides_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  interval USER-DEFINED NOT NULL,
  price_rupees numeric NOT NULL,
  commission_discount_percent numeric,
  extra_radius_km integer,
  priority_level integer DEFAULT 0,
  included_features ARRAY DEFAULT ARRAY[]::feature_key[],
  is_active boolean DEFAULT true,
  trial_days integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscription_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  subscription_id uuid NOT NULL,
  subscription_type text NOT NULL CHECK (subscription_type = ANY (ARRAY['helper'::text, 'customer'::text])),
  feature_used USER-DEFINED NOT NULL,
  usage_count integer DEFAULT 1,
  metadata jsonb,
  used_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_usage_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_number text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  request_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['booking_issue'::text, 'payment_issue'::text, 'helper_complaint'::text, 'technical_issue'::text, 'account_issue'::text, 'refund_request'::text, 'other'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'assigned'::text, 'in_progress'::text, 'waiting_response'::text, 'resolved'::text, 'closed'::text])),
  subject text NOT NULL,
  description text NOT NULL,
  attachments jsonb,
  assigned_to uuid,
  assigned_at timestamp with time zone,
  first_response_at timestamp with time zone,
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  resolution_notes text,
  satisfaction_rating integer CHECK (satisfaction_rating >= 1 AND satisfaction_rating <= 5),
  satisfaction_feedback text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.surge_pricing_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  category_id uuid,
  urgency_level USER-DEFINED,
  day_of_week integer,
  hour_start time without time zone,
  hour_end time without time zone,
  multiplier numeric NOT NULL DEFAULT 1.0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT surge_pricing_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  id integer NOT NULL DEFAULT nextval('system_settings_id_seq'::regclass),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ticket_activity_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_id uuid NOT NULL,
  actor_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['created'::text, 'assigned'::text, 'status_changed'::text, 'priority_changed'::text, 'message_sent'::text, 'resolved'::text, 'closed'::text, 'reopened'::text])),
  old_value text,
  new_value text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ticket_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_activity_log_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT ticket_activity_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ticket_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  attachments jsonb,
  is_internal boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT ticket_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.typing_indicators (
  request_id uuid NOT NULL,
  user_id uuid NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT typing_indicators_pkey PRIMARY KEY (request_id, user_id),
  CONSTRAINT typing_indicators_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT typing_indicators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  achievement_id uuid NOT NULL,
  earned_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  progress_data jsonb,
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  progress_value integer DEFAULT 0,
  is_displayed boolean DEFAULT false,
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badge_definitions(id)
);
CREATE TABLE public.user_bonuses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  bonus_type text NOT NULL CHECK (bonus_type = ANY (ARRAY['welcome'::text, 'referral'::text, 'campaign'::text, 'loyalty'::text, 'promotion'::text])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  status text NOT NULL DEFAULT 'credited'::text CHECK (status = ANY (ARRAY['pending'::text, 'credited'::text, 'expired'::text, 'cancelled'::text])),
  description text,
  credited_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_bonuses_pkey PRIMARY KEY (id),
  CONSTRAINT user_bonuses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_notification_prefs (
  user_id uuid NOT NULL,
  push_enabled boolean DEFAULT true,
  in_app_enabled boolean DEFAULT true,
  email_enabled boolean DEFAULT false,
  sms_enabled boolean DEFAULT false,
  quiet_hours jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_notification_prefs_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token text NOT NULL,
  device_name text NOT NULL,
  browser text,
  os text,
  ip_address text,
  location text,
  user_agent text,
  is_current boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_active_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  revoked_reason text,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_sessions_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.verification_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['aadhar'::text, 'pan'::text, 'driving_license'::text, 'passport'::text, 'voter_id'::text, 'police_verification'::text, 'address_proof'::text])),
  document_number text NOT NULL,
  document_url text NOT NULL,
  back_side_url text,
  selfie_url text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  rejection_reason text,
  verified_by uuid,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT verification_documents_pkey PRIMARY KEY (id),
  CONSTRAINT verification_documents_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id),
  CONSTRAINT verification_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.verification_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_user_id uuid NOT NULL,
  admin_user_id uuid NOT NULL,
  decision USER-DEFINED NOT NULL,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT verification_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT verification_reviews_helper_user_id_fkey FOREIGN KEY (helper_user_id) REFERENCES public.profiles(id),
  CONSTRAINT verification_reviews_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.verified_phones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone_number character varying NOT NULL,
  country_code character varying NOT NULL DEFAULT '+91'::character varying,
  user_id uuid NOT NULL,
  verified_at timestamp with time zone NOT NULL DEFAULT now(),
  is_primary boolean NOT NULL DEFAULT true,
  CONSTRAINT verified_phones_pkey PRIMARY KEY (id),
  CONSTRAINT verified_phones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.video_call_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid,
  customer_id uuid NOT NULL,
  helper_id uuid NOT NULL,
  call_type text NOT NULL CHECK (call_type = ANY (ARRAY['consultation'::text, 'pre_booking'::text, 'support'::text, 'training'::text])),
  provider text NOT NULL CHECK (provider = ANY (ARRAY['agora'::text, 'twilio'::text, 'jitsi'::text])),
  channel_name text NOT NULL,
  channel_token text,
  app_id text,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text, 'failed'::text])),
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  duration_seconds integer,
  recording_url text,
  is_recorded boolean DEFAULT false,
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  connection_issues jsonb,
  participants_count integer DEFAULT 2,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT video_call_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT video_call_sessions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT video_call_sessions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT video_call_sessions_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet_accounts (
  user_id uuid NOT NULL,
  available_balance numeric NOT NULL DEFAULT 0 CHECK (available_balance >= 0::numeric),
  escrow_balance numeric NOT NULL DEFAULT 0 CHECK (escrow_balance >= 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_accounts_pkey PRIMARY KEY (user_id),
  CONSTRAINT wallet_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.withdrawal_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  helper_id uuid NOT NULL,
  amount_paise integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'requested'::withdrawal_status,
  bank_account_id uuid,
  payout_mode text CHECK (payout_mode = ANY (ARRAY['bank_transfer'::text, 'upi'::text])),
  target_identifier text,
  requested_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  processed_at timestamp with time zone,
  paid_at timestamp with time zone,
  failed_reason text,
  notes text,
  payout_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT withdrawal_requests_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawal_requests_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES public.profiles(id),
  CONSTRAINT withdrawal_requests_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.helper_bank_accounts(id),
  CONSTRAINT withdrawal_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT withdrawal_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.work_proofs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  proof_type text NOT NULL CHECK (proof_type = ANY (ARRAY['before'::text, 'during'::text, 'after'::text, 'issue'::text, 'completion'::text])),
  media_url text NOT NULL,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text])),
  thumbnail_url text,
  caption text,
  location_lat numeric,
  location_lng numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT work_proofs_pkey PRIMARY KEY (id),
  CONSTRAINT work_proofs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.service_requests(id),
  CONSTRAINT work_proofs_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);